title: "Yifan 's blog"
author: "Yifan"
description: "Yifan's personal blog"

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "yifanye666@gmail.com"
github_username: "yyfhust"
linkedin_username: "yifan-ye"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
    values:
      image: resources/images/Screenshot 2022-09-06 at 21.03.06.png # default site image
  - scope:
      path: ""
      type: posts
    values:
      tags:
        - Other #default tag
